function [ahLinkFixed,ahLinkSlider, ahLinkEdit,iNextY] = fnGenerateControllersForVirtualArm(strctPanel,strctVirtualArm,yStartY)
iNumLinks = length(strctVirtualArm);
ahLinkFixed = zeros(1,iNumLinks);
ahLinkSlider = zeros(1,iNumLinks);
ahLinkEdit = zeros(1,iNumLinks);


if (ismac)
       virt_arm_field_height = 24;
else
       virt_arm_field_height = 20;
end


for k=1:iNumLinks
    
ahLinkFixed(k) = uicontrol('style','checkbox','String',...
    strctVirtualArm(k).m_strName,...
    'HorizontalAlignment','left',...
    'Position',[10 strctPanel.m_aiRightPanelSize(4)-yStartY-k*virt_arm_field_height 150 virt_arm_field_height-5],...
    'parent',strctPanel.m_ahRightPanels(2),'FontSize',6,'value',strctVirtualArm(k).m_bFixed,'callback',  {@fnCallback,'LinkFixValue',k});
if strctVirtualArm(k).m_bFixed
    strEnable = 'off';
else
     strEnable = 'on';
end

if ~isempty(strctVirtualArm(k).m_afDiscreteValues)
    iIndex = find(strctVirtualArm(k).m_afDiscreteValues == strctVirtualArm(k).m_fValue);
    iNumPosValues= length(strctVirtualArm(k).m_afDiscreteValues);
ahLinkSlider(k) = uicontrol('style','slider','units','pixels','position',...
    [100 strctPanel.m_aiRightPanelSize(4)-yStartY-k*virt_arm_field_height 120 virt_arm_field_height-5],...
    'parent',strctPanel.m_ahRightPanels(2),...
    'min',1,...
    'max',iNumPosValues,...
    'SliderStep',[1/iNumPosValues 1/iNumPosValues],...
    'value',iIndex,...
    'callback', {@fnCallback,'LinkSliderValue',k},'visible','on','enable',strEnable);
else
    fRange = strctVirtualArm(k).m_fMax-strctVirtualArm(k).m_fMin;
    ahLinkSlider(k) = uicontrol('style','slider','units','pixels','position',...
        [100 strctPanel.m_aiRightPanelSize(4)-yStartY-k*virt_arm_field_height 120 virt_arm_field_height-5],...
        'parent',strctPanel.m_ahRightPanels(2),...
        'min',strctVirtualArm(k).m_fMin,...
        'max',strctVirtualArm(k).m_fMax,...
        'SliderStep',[1/fRange 1/fRange*10],'callback', {@fnCallback,'LinkSliderValue',k},'visible','on','enable',strEnable);
end

ahLinkEdit(k) = uicontrol('style','edit','units','pixels','position',...
    [230 strctPanel.m_aiRightPanelSize(4)-yStartY-k*virt_arm_field_height 60 virt_arm_field_height-5],...
    'parent',strctPanel.m_ahRightPanels(2),...
    'String',sprintf('%.2f',strctVirtualArm(k).m_fValue),...
    'backgroundcolor',[1 1 1],'fontsize',9,...
    'callback', {@fnCallback,'LinkEditValue',k},'visible','on','enable',strEnable);
end
iNextY = strctPanel.m_aiRightPanelSize(4)-yStartY-(iNumLinks+1)*virt_arm_field_height;
return;

function fnCallback(a,b,strEvent,varargin)
global g_strctModule
feval(g_strctModule.m_hCallbackFunc,strEvent,varargin{:});
return;
