function fnFirstInvalidate()
global g_strctModule
g_strctModule.m_bFirstInvalidate = false;
a2fXYZ_To_CRS = inv(g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a2fM) * inv(g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a2fReg); %#ok
[a2fCrossSectionXY, apt3fPlanePointsXY] = fnResampleCrossSection(g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a3fVol, a2fXYZ_To_CRS, g_strctModule.m_strctCrossSectionXY); %#ok
[a2fCrossSectionYZ, apt3fPlanePointsYZ] = fnResampleCrossSection(g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a3fVol, a2fXYZ_To_CRS, g_strctModule.m_strctCrossSectionYZ); %#ok
[a2fCrossSectionXZ, apt3fPlanePointsXZ] = fnResampleCrossSection(g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a3fVol, a2fXYZ_To_CRS, g_strctModule.m_strctCrossSectionXZ); %#ok

 
[pt2fXY_YZ_1, pt2fXY_YZ_2,...
          pt2fXY_XZ_1, pt2fXY_XZ_2, ...
          pt2fXZ_YZ_1, pt2fXZ_YZ_2,...
          pt2fXZ_XY_1, pt2fXZ_XY_2,...
          pt2fYZ_XY_1, pt2fYZ_XY_2,...
          pt2fYZ_XZ_1, pt2fYZ_XZ_2]= fnComputeCrossSectionIntersections();


g_strctModule.m_strctPanel.m_hPlaneXY = surface(reshape(apt3fPlanePointsXY(1,:),2,2),...
    reshape(apt3fPlanePointsXY(2,:),2,2),...
    reshape(apt3fPlanePointsXY(3,:),2,2), ...
    'parent',g_strctModule.m_strctPanel.m_strct3D.m_hAxes,'FaceAlpha',0.2,'FaceColor',[0 0 1 ],...
    'UIContextMenu', g_strctModule.m_strctPanel.m_hMenu3D);

g_strctModule.m_strctPanel.m_hPlaneYZ = surface(reshape(apt3fPlanePointsYZ(1,:),2,2),...
    reshape(apt3fPlanePointsYZ(2,:),2,2),...
    reshape(apt3fPlanePointsYZ(3,:),2,2), ...
    'parent',g_strctModule.m_strctPanel.m_strct3D.m_hAxes,'FaceAlpha',0.2,'FaceColor',[1 0 0],...
    'UIContextMenu', g_strctModule.m_strctPanel.m_hMenu3D);

g_strctModule.m_strctPanel.m_hPlaneXZ = surface(reshape(apt3fPlanePointsXZ(1,:),2,2),...
    reshape(apt3fPlanePointsXZ(2,:),2,2),...
    reshape(apt3fPlanePointsXZ(3,:),2,2), 'parent',...
    g_strctModule.m_strctPanel.m_strct3D.m_hAxes,'FaceAlpha',0.2,'FaceColor',[0 1 0],...
    'UIContextMenu', g_strctModule.m_strctPanel.m_hMenu3D);

g_strctModule.m_strctPanel.m_strctXY.m_hLineYZ = plot(g_strctModule.m_strctPanel.m_strctXY.m_hAxes, ...
    [pt2fXY_YZ_1(1),pt2fXY_YZ_2(1)],[pt2fXY_YZ_1(2),pt2fXY_YZ_2(2)],'r');

g_strctModule.m_strctPanel.m_strctXY.m_hLineXZ = plot(g_strctModule.m_strctPanel.m_strctXY.m_hAxes, ...
    [pt2fXY_XZ_1(1),pt2fXY_XZ_2(1)],[pt2fXY_XZ_1(2),pt2fXY_XZ_2(2)],'g');

g_strctModule.m_strctPanel.m_strctXZ.m_hLineYZ = plot(g_strctModule.m_strctPanel.m_strctXZ.m_hAxes, ...
    [pt2fXZ_YZ_1(1),pt2fXZ_YZ_2(1)],[pt2fXZ_YZ_1(2),pt2fXZ_YZ_2(2)],'r');
g_strctModule.m_strctPanel.m_strctXZ.m_hLineXY = plot(g_strctModule.m_strctPanel.m_strctXZ.m_hAxes, ...
    [pt2fXZ_XY_1(1),pt2fXZ_XY_2(1)],[pt2fXZ_XY_1(2),pt2fXZ_XY_2(2)],'b');


g_strctModule.m_strctPanel.m_strctYZ.m_hLineXY = plot(g_strctModule.m_strctPanel.m_strctYZ.m_hAxes, ...
    [pt2fYZ_XY_1(1),pt2fYZ_XY_2(1)],[pt2fYZ_XY_1(2),pt2fYZ_XY_2(2)],'b');
g_strctModule.m_strctPanel.m_strctYZ.m_hLineXZ = plot(g_strctModule.m_strctPanel.m_strctYZ.m_hAxes, ...
    [pt2fYZ_XZ_1(1),pt2fYZ_XZ_2(1)],[pt2fYZ_XZ_1(2),pt2fYZ_XZ_2(2)],'g');
set(g_strctModule.m_strctPanel.m_hWindowsPanel,'visible','on');
axes(g_strctModule.m_strctPanel.m_strct3D.m_hAxes); %#ok
camlight('right')
lighting('gouraud');

 return;