function astrctMesh = fnBuildTargetMesh(strctTarget, bSelected)
global g_strctModule    
    % Generate three cubes with different colors and different radii
    % (too problematic to generate a spherical triangular mesh. Delaunay is
    % CRAP!
a2fCRS_To_XYZ = g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a2fReg*g_strctModule.m_acAnatVol{g_strctModule.m_iCurrAnatVol}.m_a2fM; 
    

if bSelected
    a2fColors = [1 0 0;
                 0 1 0;
                 0 0 1];
else
    a2fColors = [0.5 0.5 0;
                 0.5 0.5 0;
                 0.5 0.5 0];
end
pt3fPositionMM = a2fCRS_To_XYZ * [strctTarget.m_pt3fPositionVoxel;1];

astrctMesh(1) = fnBuildCubeMesh(...
    pt3fPositionMM(1),...
    pt3fPositionMM(2),....
    pt3fPositionMM(3),...
    0.5,0.5,0.5,a2fColors(1,:));
astrctMesh(2)= fnBuildCubeMesh(...
    pt3fPositionMM(1),...
    pt3fPositionMM(2),....
    pt3fPositionMM(3),...
    1,1,1,a2fColors(2,:));
astrctMesh(3) = fnBuildCubeMesh(...
    pt3fPositionMM(1),...
    pt3fPositionMM(2),....
    pt3fPositionMM(3),...
    2,2,2,a2fColors(3,:));
 
    
return;